# Generated by Django 3.2.5 on 2021-07-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='mode',
            name='data',
            field=models.JSONField(default={}, verbose_name='Data'),
        ),
        migrations.AlterUniqueTogether(
            name='mode',
            unique_together={('device', 'name')},
        ),
    ]
