# Generated by Django 3.2.5 on 2021-07-04 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_alter_mode_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mode',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modes', to='devices.device'),
        ),
    ]
