# Generated by Django 3.2.5 on 2021-07-04 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_auto_20210704_1644'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mode',
            unique_together={('device', 'name', 'data')},
        ),
    ]
